In [1]:
import pandas as pd
import numpy as np
import warnings
import seaborn as sns
from pylab import mpl

# best font and style settings for notebook
warnings.filterwarnings('ignore')
sns.set_style("white")
mpl.rcParams['font.family'] = '微软雅黑'

from tqdm import tqdm_notebook

def run_simulation_numpy(num_people, N):
    # 初始化 NumPy 数组
    ids = np.arange(1, num_people + 1)
    results = np.full((num_people, N), -1)  # 结果矩阵

    for i in tqdm_notebook(range(N)):
        status = np.ones(num_people, dtype=int)
        killed_turn = np.full(num_people, -1)
        
        for turn in range(num_people):
            alive_ids = np.where(status == 1)[0]  # 获取当前存活的ID索引
            if alive_ids.size == 0:  # 如果没有存活者，提前退出循环
                break
            
            kill_idx = np.random.choice(alive_ids)  # 选择要淘汰的ID索引
            status[kill_idx] = 0  # 标记为淘汰
            killed_turn[kill_idx] = turn + 1  # 记录淘汰回合
        
        results[:, i] = killed_turn  # 将结果存储到结果矩阵

    # 转换为 DataFrame
    df_simul = pd.DataFrame(results, index=ids, columns=[f'turn_{i}' for i in range(N)])
    df_simul.index.name = "id"
    
    return df_simul

# 参数设置
num_people = 600
N = 2000

# 运行模拟
df_simul = run_simulation_numpy(num_people, N)

df_simul

  0%|          | 0/2000 [00:00<?, ?it/s]

,turn_0,turn_1,turn_2,turn_3,turn_4,turn_5,turn_6,turn_7,turn_8,turn_9,...,turn_1990,turn_1991,turn_1992,turn_1993,turn_1994,turn_1995,turn_1996,turn_1997,turn_1998,turn_1999
id,,,,,,,,,,,,,,,,,,,,,
1,300,403,393,355,549,235,123,402,413,22,...,218,392,289,197,372,526,21,500,570,281
2,116,228,297,51,133,323,107,363,50,72,...,201,222,106,496,503,10,467,507,267,297
3,64,47,290,68,472,295,382,228,295,138,...,295,442,511,391,304,485,163,459,60,538
4,115,178,573,257,440,180,243,353,443,290,...,270,210,72,156,253,322,531,68,599,588
5,111,389,377,93,121,254,257,113,181,491,...,100,115,100,102,464,82,47,354,46,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,523,116,470,76,512,499,493,417,539,129,...,324,547,527,318,235,65,518,345,15,283
597,467,413,43,469,251,560,129,412,337,46,...,390,412,74,151,354,201,196,461,343,355
598,212,336,349,318,509,325,566,202,296,327,...,571,81,502,228,27,203,289,483,252,396
599,453,397,96,230,36,579,438,192,370,545,...,411,585,188,552,15,550,591,1,132,135
600,207,8,478,401,555,148,393,43,571,342,...,233,400,499,56,585,181,316,349,515,187

In [3]:
df_simul.reset_index()

,id,turn_0,turn_1,turn_2,turn_3,turn_4,turn_5,turn_6,turn_7,turn_8,...,turn_1990,turn_1991,turn_1992,turn_1993,turn_1994,turn_1995,turn_1996,turn_1997,turn_1998,turn_1999
0,1,300,403,393,355,549,235,123,402,413,...,218,392,289,197,372,526,21,500,570,281
1,2,116,228,297,51,133,323,107,363,50,...,201,222,106,496,503,10,467,507,267,297
2,3,64,47,290,68,472,295,382,228,295,...,295,442,511,391,304,485,163,459,60,538
3,4,115,178,573,257,440,180,243,353,443,...,270,210,72,156,253,322,531,68,599,588
4,5,111,389,377,93,121,254,257,113,181,...,100,115,100,102,464,82,47,354,46,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,596,523,116,470,76,512,499,493,417,539,...,324,547,527,318,235,65,518,345,15,283
596,597,467,413,43,469,251,560,129,412,337,...,390,412,74,151,354,201,196,461,343,355
597,598,212,336,349,318,509,325,566,202,296,...,571,81,502,228,27,203,289,483,252,396
598,599,453,397,96,230,36,579,438,192,370,...,411,585,188,552,15,550,591,1,132,135
599,600,207,8,478,401,555,148,393,43,571,...,233,400,499,56,585,181,316,349,515,187